[[http://melpa.org/#/emms-player-simple-mpv][file:http://melpa.org/packages/emms-player-simple-mpv-badge.svg]]
[[http://stable.melpa.org/#/emms-player-simple-mpv][file:http://stable.melpa.org/packages/emms-player-simple-mpv-badge.svg]]

* emms-player-simple-mpv

** What is it ?

  emms-player-simple-mpv.el is an extension of emms-player-simple.el for mpv JSON IPC.
  It provides basic functions for interface defined in EMMS ( [[https://www.gnu.org/software/emms/][The Emacs Multimedia System]] ).

  emms-player-simple-mpv-control-functions.el provides other functions to control mpv.

** Requirements

   + GNU Emacs 24 or later
   + EMMS 4.0 or later
   + mpv v0.7 or later ( [[https://github.com/mpv-player/mpv]] )

   Tested with GNU Emacs 24.5 (emacs-mac-app @5.7_0), EMMS 4.0, mpv @0.8.3_0.

** Setup

   #+BEGIN_SRC emacs-lisp
     (add-to-list 'load-path "/path/to/emms-player-simple-mpv")
     (require 'emms-player-simple-mpv)
     ;; If you use other control functions, load it.
     (require 'emms-player-simple-mpv-control-functions)
   #+END_SRC

** Usage

   #+BEGIN_SRC emacs-lisp
     ;; An example of setting like emms-player-mplayer.el
     ;; `emms-player-mpv' is defined by `define-emms-simple-player-mpv'.
     (define-emms-simple-player-mpv mpv '(file url streamlist playlist)
         (concat "\\`\\(http[s]?\\|mms\\)://\\|"
                 (apply #'emms-player-simple-regexp
                        "pls"
                        emms-player-base-format-list))
         "mpv" "--no-terminal" "--force-window=no" "--audio-display=no")

     (emms-player-simple-mpv-add-to-converters
      'emms-player-mpv "." '(playlist)
      (lambda (track-name) (format "--playlist=%s" track-name)))

     (add-to-list 'emms-player-list 'emms-player-mpv)
   #+END_SRC

***** Macro: =define-emms-simple-player-mpv name types regex command &rest args=

      This macro emulates =define-emms-simple-player=. See EMMS Manual [[https://www.gnu.org/software/emms/manual/Simple-Players.html#Simple-Players][11 Simple-Players]].

***** Function: =emms-player-simple-mpv-add-to-converters player regexp types fn &optional appendp=

      This function adds =(list regexp types fn)= to player's =mpv-track-name-converters=.
      =fn= converts track name to input form
      when mpv needs specific format such as ffplay format for playing some protocols.

***** User Option: =emms-player-simple-mpv-use-volume-change-function-p=

      Default value is =t=.
      If the variable is non-nil,
      =emms-player-simple-mpv-volume-change= is used as =emms-volume-change-function= while an emms mpv player is running.

***** Some examples of defining specific emms simple players of mpv

      + [[https://github.com/momomo5717/emms-player-mpv-jp-radios]]

**** An example of setting for hydra ( [[https://github.com/abo-abo/hydra]] )

     If you use hydra.el, the following example could be useful for playing sound.
     This example emulates default key bindings of mpv player.

     #+BEGIN_SRC emacs-lisp
       (require 'hydra)
       (require 'emms-player-simple-mpv-control-functions)

       ;; (global-set-key (kbd "<f2> m") 'emms-player-simple-mpv-hydra/body)
       (defhydra emms-player-simple-mpv-hydra
         (:foreign-keys warn :hint nil)
         "
         Keyboard Control for emms simple player of mpv
       -------------------------------------------------------------
         _Q_        Quit emms-player-simple-mpv-hydra.
         ─────────────────────────────
         <left> and <right>
                  Seek backward/forward 5 seconds.
         S-<left> and S-<right>
                  Seek backward/forward 1 seconds.
         <down> and <up>
                  Seek backward/forward 1 minute.
         S-<down> and S-<upt>
                  Seek backward/forward 5 seconds.
         ─────────────────────────────
         \[ and \]  Decrease/increase current playback speed by 10 %%%%.
         \{ and \}  Halve/double current playback speed.
         <backspace>
                  Reset playback speed to normal.
         ─────────────────────────────
         < and >  Go backward/forward in the playlist.
         <retrun> Go forward in the playlist.
         ─────────────────────────────
         p / SPC  Pause (pressing again unpauses).
         ─────────────────────────────
         q        Stop playing and quit.
         ─────────────────────────────
         / and *  Decrease/increase volume.
         9 and 0  Decrease/increase volume.
         ─────────────────────────────
         m        Mute sound.
         ─────────────────────────────
         f        Toggle fullscreen.
         ─────────────────────────────
         T        Toggle stay-on-top.
       -------------------------------------------------------------

       "
         ("Q" nil)
         ("<left>"    (lambda () (interactive) (emms-seek -5)))
         ("S-<left>"  (lambda () (interactive) (emms-seek -1)))
         ("<down>"    (lambda () (interactive) (emms-seek -60)))
         ("S-<down>"  (lambda () (interactive) (emms-seek -5)))
         ("<right>"   (lambda () (interactive) (emms-seek 5)))
         ("S-<right>" (lambda () (interactive) (emms-seek 1)))
         ("<up>"      (lambda () (interactive) (emms-seek 60)))
         ("S-<up>"    (lambda () (interactive) (emms-seek 5)))
         ("["  emms-player-simple-mpv-speed-decrease)
         ("]"  emms-player-simple-mpv-speed-increase)
         ("{"  emms-player-simple-mpv-speed-halve)
         ("}"  emms-player-simple-mpv-speed-double)
         ("<backspace>" emms-player-simple-mpv-speed-normal)
         ("<" emms-player-simple-mpv-playlist-prev)
         (">" emms-player-simple-mpv-playlist-next)
         ("<return>" emms-player-simple-mpv-playlist-next)
         ("p" emms-pause)
         ("SPC" emms-pause)
         ("q" (lambda () (interactive)
                (when (y-or-n-p "Run emms-stop")
                  (emms-stop))) :exit t)
         ("/" emms-volume-lower)
         ("*" emms-volume-raise)
         ("9" emms-volume-lower)
         ("0" emms-volume-raise)
         ("m" emms-player-simple-mpv-mute)
         ("f" emms-player-simple-mpv-fullscreen)
         ("T" emms-player-simple-mpv-ontop))

     #+END_SRC

** References

     + emms-player-mpv ( [[https://github.com/dochang/emms-player-mpv]] )
     + mpv.el ( [[https://github.com/kljohann/mpv.el]] )
