* emms-player-simple-mpv

** What is it ?

  emms-player-simple-mpv.el is an extension of emms-palyer-simple.el for mpv JSON IPC.
  It provides basic functions for interface defined in EMMS ( [[https://www.gnu.org/software/emms/][The Emacs Multimedia System]] ).

  emms-player-simple-mpv-control-functions.el provides other functions to control mpv.

** Requirements

   + GNU Emacs 24 or later
   + EMMS 4.0
   + mpv v0.7 or later ( [[https://github.com/mpv-player/mpv]] )

   Tested with GNU Emacs 24.4 (emacs-mac-app @5.4_0), EMMS 4.0, mpv @0.8.3_0.

** Setup

   #+BEGIN_SRC emacs-lisp
     (add-to-list 'load-path "/path/to/emms-player-simple-mpv")
     (require 'emms-player-simple-mpv)
     ;; If you use other control functions, load it.
     (require 'emms-player-simple-mpv-control-functions)
   #+END_SRC

** Usage

   #+BEGIN_SRC emacs-lisp
     ;; An example of setting like emms-player-mplayer.el
     ;; `emms-player-mpv' is defined by `define-emms-simple-player-mpv'.
     (define-emms-simple-player-mpv mpv '(file url streamlist playlist)
         (concat "\\`\\(http[s]?\\|mms\\)://\\|"
                 (apply #'emms-player-simple-regexp
                        "pls"
                        emms-player-base-format-list))
         "mpv" "--no-terminal" "--force-window=no" "--audio-display=no")

     (emms-player-simple-mpv-add-to-converters
      'emms-player-mpv "." '(playlist)
      (lambda (track-name) (format "--playlist=%s" track-name)))

     (add-to-list 'emms-player-list 'emms-player-mpv)
   #+END_SRC

***** Macro: =define-emms-simple-player-mpv name types regex command &rest args=

      This macro emulate =define-emms-simple-player=. See EMMS Manual [[https://www.gnu.org/software/emms/manual/Simple-Players.html#Simple-Players][11 Simple-Players]].

***** Function: =emms-player-simple-mpv-add-to-converters player regexp types fn &optional appendp=

      This function adds =(list regexp types fn)= to player's =mpv-track-name-converters=.
      =fn= converts track name to input form
      when mpv needs specific format such as ffplay format for playing some protocols.

***** User Option: =emms-player-simple-mpv-use-volume-change-function-p=

      Default value is =t=.
      If the variable is non-nil,
      =emms-player-simple-mpv-volume-change= is used as =emms-volume-change-function= while a emms mpv player is running.

   Some examples of defining specific emms players : [[https://github.com/momomo5717/emms-player-mpv-jp-radios]]

** References

     + emms-player-mpv ( [[https://github.com/dochang/emms-player-mpv]] )
     + mpv.el ( [[https://github.com/kljohann/mpv.el]] )
